"""add job_offer table

Revision ID: 2b7d5b3d9f1a
Revises: 0f3656ba31e6
Create Date: 2026-03-02

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "2b7d5b3d9f1a"
down_revision: Union[str, Sequence[str], None] = "0f3656ba31e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'offerstatus') THEN
                CREATE TYPE offerstatus AS ENUM ('wysłano', '1 etap', '2 etap', '3 etap', 'umowa');
            END IF;
        END
        $$;
        """
    )

    offer_status_enum = postgresql.ENUM(
        "wysłano",
        "1 etap",
        "2 etap",
        "3 etap",
        "umowa",
        name="offerstatus",
        create_type=False,
    )

    op.create_table(
        "job_offer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("status", offer_status_enum, nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_offer_id"), "job_offer", ["id"], unique=False)
    op.create_index(op.f("ix_job_offer_title"), "job_offer", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f("ix_job_offer_title"), table_name="job_offer")
    op.drop_index(op.f("ix_job_offer_id"), table_name="job_offer")
    op.drop_table("job_offer")

    offer_status_enum = postgresql.ENUM(
        "wysłano",
        "1 etap",
        "2 etap",
        "3 etap",
        "umowa",
        name="offerstatus",
        create_type=False,
    )
    offer_status_enum.drop(op.get_bind(), checkfirst=True)
