"""add refresh token fields to user

Revision ID: 3ecff4712589
Revises: 57432c7ca906
Create Date: 2026-04-28 14:07:09.622576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ecff4712589'
down_revision: Union[str, Sequence[str], None] = '57432c7ca906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refresh_token_hash', sa.String(), nullable=True))
    op.add_column('user', sa.Column('refresh_token_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'refresh_token_expires_at')
    op.drop_column('user', 'refresh_token_hash')
    # ### end Alembic commands ###
