"""add notes to job offer

Revision ID: 42ae8afa7499
Revises: 3c1a0f2f7b2e
Create Date: 2026-03-16 23:21:55.181058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42ae8afa7499'
down_revision: Union[str, Sequence[str], None] = '3c1a0f2f7b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_id'), table_name='interview')
    op.drop_table('interview')
    op.drop_index(op.f('ix_user_profile_id'), table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_job_application_company'), table_name='job_application')
    op.drop_index(op.f('ix_job_application_id'), table_name='job_application')
    op.drop_index(op.f('ix_job_application_position'), table_name='job_application')
    op.drop_table('job_application')
    op.add_column('job_offer', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_offer', 'notes')
    op.create_table('job_application',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('TO_APPLY', 'APPLIED', 'INTERVIEWING', 'OFFER', 'REJECTED', name='jobstatus'), autoincrement=False, nullable=False),
    sa.Column('listing_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description_raw', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('match_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('job_application_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('job_application_pkey'))
    )
    op.create_index(op.f('ix_job_application_position'), 'job_application', ['position'], unique=False)
    op.create_index(op.f('ix_job_application_id'), 'job_application', ['id'], unique=False)
    op.create_index(op.f('ix_job_application_company'), 'job_application', ['company'], unique=False)
    op.create_table('user_profile',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cv_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('user_profile_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_profile_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('user_profile_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_profile_id'), 'user_profile', ['id'], unique=False)
    op.create_table('interview',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('HR', 'TECH', 'FINAL', name='interviewtype'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['job_application.id'], name=op.f('interview_application_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('interview_pkey'))
    )
    op.create_index(op.f('ix_interview_id'), 'interview', ['id'], unique=False)
    # ### end Alembic commands ###
