"""add indexes on user_id and timestamp columns

Revision ID: 57432c7ca906
Revises: 90d905edceb9
Create Date: 2026-04-28 12:41:49.876347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57432c7ca906'
down_revision: Union[str, Sequence[str], None] = '90d905edceb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_expense_timestamp'), 'expense', ['timestamp'], unique=False)
    op.create_index(op.f('ix_expense_user_id'), 'expense', ['user_id'], unique=False)
    op.create_index(op.f('ix_goal_user_id'), 'goal', ['user_id'], unique=False)
    op.create_index(op.f('ix_habit_user_id'), 'habit', ['user_id'], unique=False)
    op.create_index(op.f('ix_meal_log_created_at'), 'meal_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_meal_log_user_id'), 'meal_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_task_user_id'), 'task', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_user_id'), table_name='task')
    op.drop_index(op.f('ix_meal_log_user_id'), table_name='meal_log')
    op.drop_index(op.f('ix_meal_log_created_at'), table_name='meal_log')
    op.drop_index(op.f('ix_habit_user_id'), table_name='habit')
    op.drop_index(op.f('ix_goal_user_id'), table_name='goal')
    op.drop_index(op.f('ix_expense_user_id'), table_name='expense')
    op.drop_index(op.f('ix_expense_timestamp'), table_name='expense')
    # ### end Alembic commands ###
