"""add_expense_model

Revision ID: 68b1d4566fc7
Revises: 42ae8afa7499
Create Date: 2026-03-21 09:28:36.506435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types


# revision identifiers, used by Alembic.
revision: str = '68b1d4566fc7'
down_revision: Union[str, Sequence[str], None] = '42ae8afa7499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.Enum('OPLATY', 'HUSTLE', 'LIFESTYLE', 'INCOME', name='expensecategory'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('timestamp', app.db.types.NaiveDateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_id'), 'expense', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expense_id'), table_name='expense')
    op.drop_table('expense')
    # ### end Alembic commands ###
