"""add_donation_table

Revision ID: e3769b1bbb0d
Revises: 89cd7e0c9692
Create Date: 2026-05-29 17:13:53.322273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types


# revision identifiers, used by Alembic.
revision: str = 'e3769b1bbb0d'
down_revision: Union[str, Sequence[str], None] = '89cd7e0c9692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_session_id', sa.String(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('supporter_name', sa.String(length=100), nullable=True),
    sa.Column('supporter_email', sa.String(length=254), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'EXPIRED', name='donationstatus'), nullable=False),
    sa.Column('created_at', app.db.types.NaiveDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donation_created_at'), 'donation', ['created_at'], unique=False)
    op.create_index(op.f('ix_donation_id'), 'donation', ['id'], unique=False)
    op.create_index(op.f('ix_donation_status'), 'donation', ['status'], unique=False)
    op.create_index(op.f('ix_donation_stripe_session_id'), 'donation', ['stripe_session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donation_stripe_session_id'), table_name='donation')
    op.drop_index(op.f('ix_donation_status'), table_name='donation')
    op.drop_index(op.f('ix_donation_id'), table_name='donation')
    op.drop_index(op.f('ix_donation_created_at'), table_name='donation')
    op.drop_table('donation')
    # ### end Alembic commands ###
