"""add soft delete to expense goal task meal_log job_offer

Revision ID: e65bf023f92e
Revises: 3ecff4712589
Create Date: 2026-04-28 14:24:40.593687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e65bf023f92e'
down_revision: Union[str, Sequence[str], None] = '3ecff4712589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('goal', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('job_offer', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('meal_log', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'deleted_at')
    op.drop_column('meal_log', 'deleted_at')
    op.drop_column('job_offer', 'deleted_at')
    op.drop_column('goal', 'deleted_at')
    op.drop_column('expense', 'deleted_at')
    # ### end Alembic commands ###
